School.Management.MVC/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Management.Core.Entities;
using School.Management.Services;

namespace School.Management.MVC.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService studentService;
        public StudentController(IStudentService _studentService)
        {
            try
            {
                studentService = _studentService;
            }
            catch(Exception ex)
            {

            }
        }
        public async System.Threading.Tasks.Task<IActionResult> IndexAsync()
        {
            var services = this.HttpContext.RequestServices;
            var classservice = (IClassService)services.GetService(typeof(IClassService));
            var classes = await classservice.GetAllAsync(0);


            List<SelectListItem> items = classes.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.ClassName,
                    Value = a.ClassID.ToString(),
                    Selected = false
                };
            });
          
            ViewBag.classes = items;
            List<Student> listofstudent = await studentService.GetAllAsync(1);
            return View(listofstudent);
        }
        [HttpGet]
        [ActionName("Create")]
        public async Task<IActionResult> CreateGetAsync(Student student)
        {
            // studentService.Add(student);

            var services = this.HttpContext.RequestServices;
            var classservice = (IClassService)services.GetService(typeof(IClassService));
            var classes = await classservice.GetAllAsync(0);
            student.Class = null;
            ViewBag.Classes = classes;


            List<SelectListItem> items = classes.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.ClassName,
                    Value = a.ClassID.ToString(),
                    Selected = false
                };
            });
            ViewBag.items = items;
            return View();
        }

        [HttpGet]        
        public async Task<ActionResult> EditAsync(int   id)
        {
            // Student student;
       
            Student student = await studentService.GetByIdAsync(id);
            return View(student); 
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Student student)
        {
            if (ModelState.IsValid)
            {
                await studentService.Update(student);
            }
            return View(student);
        }


        [HttpGet]
        public async Task<ActionResult> DeleteAsync(int id)
        {
            // Student student;

            Student student = await studentService.GetByIdAsync(id);
            return View(student);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int  id)
        {
            if (ModelState.IsValid)
            {
                Student student = await studentService.GetByIdAsync(id);
                View(student);
                await studentService.Delete(id);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ActionName("Create")]
        public async System.Threading.Tasks.Task<IActionResult> CreatePostAsync(Student student, List<SelectListItem> items)
   
        {
            string ClassSelected = Request.Form["ClassName"].ToString();
        
            var p = items;
            student.Class = new Class()
            {
                ClassID = Convert.ToInt32(ClassSelected),
                ClassName = "Std " + ClassSelected.ToString()
            };
            if (ModelState.IsValid)
            {
                await studentService.Add(student);
            }
            return View();
        }
    }
}

School.Management.MVC/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Management.Core.Entities;
using School.Management.Services;

namespace School.Management.MVC.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ISubjectService  subjectService;
     

        public SubjectController(ISubjectService _subjectService)
        {
            try
            {
                subjectService = _subjectService;
            }
            catch (Exception ex)
            {

            }
        }

        public async Task<IActionResult> Index()
        {
            int Yearid = 1;          
            var Subjects =   await   subjectService.GetAllAsync(Yearid);
            ViewBag.Year = Yearid;
            return View(Subjects);
        }
        [HttpGet]
        [Route("Subject/Create")]
        public async Task<IActionResult> CreateAsync(Subject subject)
        {
            if (ModelState.IsValid)
            {
                var services = this.HttpContext.RequestServices;
                var classservice = (IClassService)services.GetService(typeof(IClassService));
                var classes = await classservice.GetAllAsync(0);
                subject.classes = (IList<Class>)classes;

            }        
            return View(subject);
        }   

        [HttpPost]
        [Route("Subject/Create")]
        public async Task<IActionResult> CreatePost(Subject subject, List<Class> classes)
        {
            subject.classes = classes;
            if (ModelState.IsValid)
            {
                await subjectService.Add(subject);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            Subject subject = await subjectService.GetByIdAsync(id);
            return View(subject);
        }

        [HttpPost]
        [Route("Subject/Edit")]
        public async Task<ActionResult> Edit(Subject subject, List<Class> classes)
        {
            if (ModelState.IsValid)
            {
                subject.classes = classes;
                   await subjectService.Update(subject);
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<ActionResult> DeleteAsync(int id)
        {
            // Student student;

            Subject subject = await subjectService.GetByIdAsync(id);
            return View(subject);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            if (ModelState.IsValid)
            {
                Subject subject = await subjectService.GetByIdAsync(id);
               
                await subjectService.Delete(id);
            }
            return RedirectToAction("Index");
        }

    }
}

School.Management.MVC/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Management.Core.Entities;
using School.Management.Services;

namespace School.Management.MVC.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherService teacherService;     
        public TeacherController(ITeacherService _teacherService)
        {
            try
            {
                teacherService = _teacherService;
            }
            catch (Exception ex)
            {

            }
        }
        public async Task<IActionResult> Index()
        {
            int Yearid = 1;          
            var teachers =   await teacherService.GetAllAsync(1);
            ViewBag.Year = Yearid;
            return View(teachers);
        }

        [HttpGet]
        [Route("Teacher/Create")]
        public async Task<IActionResult> CreateAsync(Teacher teacher )
        {
            if (ModelState.IsValid)
            {
                var services = this.HttpContext.RequestServices;
                var classservice = (IClassService)services.GetService(typeof(IClassService));
                var classes = await classservice.GetAllAsync(0);
                teacher.classes = (List<Class>)classes;

            }
            return View(teacher);
        }

        [HttpPost]
        [Route("Teacher/Create")]
        public async Task<IActionResult> CreatePost(Teacher teacher , List<Class> classes)
        {
            teacher.classes = classes;
            if (ModelState.IsValid)
            {
                await teacherService.Add(teacher);
            }
            return RedirectToAction("Index");
        }

    }
}

School.Management.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School.Management.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">School.Management.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1" style="font-family:Arial, Helvetica, sans-serif0;background-color:aqua">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Subjects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teachers</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - School.Management.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>